server:
  port: 83

spring:
  application:
    name: cloud-alibaba-nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-uri:
  nacos-user-service: http://cloud-alibaba-nacos-provider-payment
