server:
  port: 9002

spring:
  application:
    name: cloud-alibaba-nacos-provider-payment
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 111.231.89.200:1111


management:
  endpoints:
    web:
      exposure:
        include: "*"