server:
  port: 2003

spring:
  application:
    name: cloud-seata-account-service
  cloud:
    alibaba:
      seata:
        # 事务组的名称要与seata-server中对应
        tx-service-group: bay_tx_group
    nacos:
      discovery:
        server-addr: 111.231.89.200:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.89.200:3306/seata_account
    username: baymux
    password: BAY_mysql@33289


feign:
  hystrix:
    enabled: false


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info
