server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，职责睡觉哦维护服务实例，不需要检索服务
    fetch-registry: false
    # 设置与Euraka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    # 关闭自我保护机制，保证不可用服务被即使剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000

