server:
  port: 2002

spring:
  application:
    name: cloud-seata-storage-service
  cloud:
    alibaba:
      seata:
        # 事务组的名称要与seata-server中对应
        tx-service-group: bay_tx_group
    nacos:
      discovery:
        server-addr: 111.231.89.200:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.89.200:3306/seata_storage
    username: baymu
    password: 111111


feign:
  hystrix:
    enabled: false


mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    io:
      seata: info